"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_landing_portal_api
from rrap_mds_is_landing_portal_api.model.access_level import AccessLevel
from rrap_mds_is_landing_portal_api.model.intended_user_type import IntendedUserType
globals()['AccessLevel'] = AccessLevel
globals()['IntendedUserType'] = IntendedUserType
from rrap_mds_is_landing_portal_api.model.report_component_role import ReportComponentRole


class TestReportComponentRole(unittest.TestCase):
    """ReportComponentRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportComponentRole(self):
        """Test ReportComponentRole"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReportComponentRole()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
