"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import rrap_mds_is_landing_portal_api
from rrap_mds_is_landing_portal_api.api.user_access_control_api import UserAccessControlApi  # noqa: E501


class TestUserAccessControlApi(unittest.TestCase):
    """UserAccessControlApi unit test stubs"""

    def setUp(self):
        self.api = UserAccessControlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_access_report(self):
        """Test case for generate_access_report

        Generate Access Report  # noqa: E501
        """
        pass

    def test_get_pending_requests(self):
        """Test case for get_pending_requests

        Get Pending Access Requests  # noqa: E501
        """
        pass

    def test_get_requests(self):
        """Test case for get_requests

        Get Full User Request History  # noqa: E501
        """
        pass

    def test_request_access_change(self):
        """Test case for request_access_change

        Request Access Change  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
