"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_landing_portal_api
from rrap_mds_is_landing_portal_api.model.request_status import RequestStatus
globals()['RequestStatus'] = RequestStatus
from rrap_mds_is_landing_portal_api.model.access_request_status_change import AccessRequestStatusChange


class TestAccessRequestStatusChange(unittest.TestCase):
    """AccessRequestStatusChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessRequestStatusChange(self):
        """Test AccessRequestStatusChange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessRequestStatusChange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
