"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_landing_portal_api
from rrap_mds_is_landing_portal_api.model.component_name import ComponentName
from rrap_mds_is_landing_portal_api.model.report_component_role import ReportComponentRole
globals()['ComponentName'] = ComponentName
globals()['ReportComponentRole'] = ReportComponentRole
from rrap_mds_is_landing_portal_api.model.report_authorisation_component import ReportAuthorisationComponent


class TestReportAuthorisationComponent(unittest.TestCase):
    """ReportAuthorisationComponent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportAuthorisationComponent(self):
        """Test ReportAuthorisationComponent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReportAuthorisationComponent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
