"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import rrap_mds_is_landing_portal_api
from rrap_mds_is_landing_portal_api.api.admin_access_control_api import AdminAccessControlApi  # noqa: E501


class TestAdminAccessControlApi(unittest.TestCase):
    """AdminAccessControlApi unit test stubs"""

    def setUp(self):
        self.api = AdminAccessControlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_note_access_control_admin_add_note_post(self):
        """Test case for add_note_access_control_admin_add_note_post

        Add Note  # noqa: E501
        """
        pass

    def test_all_pending_request_history_access_control_admin_all_pending_request_history_get(self):
        """Test case for all_pending_request_history_access_control_admin_all_pending_request_history_get

        All Pending Request History  # noqa: E501
        """
        pass

    def test_all_request_history_access_control_admin_all_request_history_get(self):
        """Test case for all_request_history_access_control_admin_all_request_history_get

        All Request History  # noqa: E501
        """
        pass

    def test_change_request_state_access_control_admin_change_request_state_post(self):
        """Test case for change_request_state_access_control_admin_change_request_state_post

        Change Request State  # noqa: E501
        """
        pass

    def test_do_delete_request_access_control_admin_delete_request_post(self):
        """Test case for do_delete_request_access_control_admin_delete_request_post

        Do Delete Request  # noqa: E501
        """
        pass

    def test_user_pending_request_history_access_control_admin_user_pending_request_history_get(self):
        """Test case for user_pending_request_history_access_control_admin_user_pending_request_history_get

        User Pending Request History  # noqa: E501
        """
        pass

    def test_user_request_history_access_control_admin_user_request_history_get(self):
        """Test case for user_request_history_access_control_admin_user_request_history_get

        User Request History  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
