"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_landing_portal_api
from rrap_mds_is_landing_portal_api.model.request_add_note import RequestAddNote


class TestRequestAddNote(unittest.TestCase):
    """RequestAddNote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestAddNote(self):
        """Test RequestAddNote"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestAddNote()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
