"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_landing_portal_api
from rrap_mds_is_landing_portal_api.model.request_status import RequestStatus
globals()['RequestStatus'] = RequestStatus
from rrap_mds_is_landing_portal_api.model.request_access_table_item import RequestAccessTableItem


class TestRequestAccessTableItem(unittest.TestCase):
    """RequestAccessTableItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestAccessTableItem(self):
        """Test RequestAccessTableItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestAccessTableItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
