"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_landing_portal_api
from rrap_mds_is_landing_portal_api.model.report_authorisation_component import ReportAuthorisationComponent
globals()['ReportAuthorisationComponent'] = ReportAuthorisationComponent
from rrap_mds_is_landing_portal_api.model.access_report import AccessReport


class TestAccessReport(unittest.TestCase):
    """AccessReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessReport(self):
        """Test AccessReport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessReport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
