"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_landing_portal_api
from rrap_mds_is_landing_portal_api.model.status import Status
globals()['Status'] = Status
from rrap_mds_is_landing_portal_api.model.change_state_status import ChangeStateStatus


class TestChangeStateStatus(unittest.TestCase):
    """ChangeStateStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeStateStatus(self):
        """Test ChangeStateStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChangeStateStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
