"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_landing_portal_api
from rrap_mds_is_landing_portal_api.model.request_access_table_item import RequestAccessTableItem
globals()['RequestAccessTableItem'] = RequestAccessTableItem
from rrap_mds_is_landing_portal_api.model.access_request_list import AccessRequestList


class TestAccessRequestList(unittest.TestCase):
    """AccessRequestList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessRequestList(self):
        """Test AccessRequestList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessRequestList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
